name: card_settings
description: A flutter package for building card based settings forms. This includes a library of pre-built form field widgets.
version: 1.2.2
author: Jeff Jorczak <jeff@jorczak.com>
homepage: https://github.com/codegrue/card_settings

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^0.2.6
  flutter_masked_text: ^0.8.0
  intl: ^0.16.0
  meta: ^1.1.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.63.0.flutter-4c9689c1d2 <3.0.0"

flutter:
  uses-material-design: true
